language: php

php:
  - 5.4
  - 5.5

install:
  - composer install

script:
  - mkdir -p tests/temp
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration tests/config.xml tests/cases/

after_script:
  - php vendor/bin/coveralls -v
