parameters:
    request:
        class: Csfd\Request

services:
    urlBuilder:
        class: Csfd\Networking\UrlBuilder
        factory_class: Csfd\Networking\UrlBuilder
        factory_method: factory
        arguments: [%root%/urls.yml]
    authenticator:
        class: Csfd\Authentication\Authenticator
        arguments: [@urlBuilder, @parsers.user, @parsers.auth, @networking]
    networking:
        class: Csfd\Networking\RequestFactory
        calls:
            - [setRequestClass, [Csfd\Networking\Request]]
    search:
        class: Csfd\Search
        arguments: [@urlBuilder, @networking, @parsers.search, @repo.users, @repo.movies]
    parsers:
        user:
            class: Csfd\Parsers\User
        movie:
            class: Csfd\Parsers\Movie
        search:
            class: Csfd\Parsers\Search
        auth:
            class: Csfd\Parsers\Authentication
    repo:
        users:
            class: Csfd\Repositories\Users
            arguments: [@authenticator, @urlBuilder, @networking]
            calls:
                - [setEntityClass, [Csfd\Entities\User]]
                - [setParserClass, [Csfd\Parsers\User]]
        movies:
            class: Csfd\Repositories\Movies
            arguments: [@authenticator, @urlBuilder, @networking]
            calls:
                - [setEntityClass, [Csfd\Entities\Movie]]
                - [setParserClass, [Csfd\Parsers\Movie]]
