parameters:
    request:
        class: Csfd\Request

services:
    urlBuilder:
        class: Csfd\Networking\UrlBuilder
        factory_class: Csfd\Networking\UrlBuilder
        factory_method: factory
        arguments: [%root%/urls.yml]
    authenticator:
        class: Csfd\Authentication\Authenticator
        arguments: [@urlBuilder, @parsers.user, @parsers.auth, @networking]
    users:
        class: Csfd\Repositories\Users
        arguments: [@authenticator, @urlBuilder, @networking]
        calls:
            - [setEntityClass, [Csfd\Entities\User]]
            - [setParserClass, [Csfd\Parsers\User]]
    parsers:
        user:
            class: Csfd\Parsers\User
        auth:
            class: Csfd\Parsers\Authentication
    networking:
        class: Csfd\Networking\RequestFactory
        calls:
            - [setRequestClass, [Csfd\Networking\Request]]
